In [1]:
from geometry_tools import representation
from geometry_tools import utils
from geometry_tools.utils import words
from geometry_tools.utils import sagewrap

from geometry_tools import lie

import numpy as np

import pdb

In [2]:
# test QQbar rep
sinpi8 = QQbar(sin(pi/8))
cospi8 = QQbar(cos(pi/8))
fourth2 = QQbar(2^(1/4))

l = QQbar(fourth2 * 2 * cospi8 + fourth2^2 + 1)

g1 = Matrix([[l, 0], [0, 1/l]])
g2 = (Matrix([[cospi8, sinpi8], [-sinpi8, cospi8]]) *
          g1 *
          Matrix([[cospi8, -sinpi8], [sinpi8, cospi8]]))

g3 = (Matrix([[fourth2^2 / 2, fourth2^2/2],
                 [-1 * fourth2^2/2, fourth2^2/2]]) * g1 *
          Matrix([[fourth2^2 / 2, -1 * fourth2^2/2],
                  [fourth2^2/2, fourth2^2/2]]))

g4 = (Matrix([[sinpi8, cospi8], [-cospi8, sinpi8]]) * g1 *
          Matrix([[sinpi8, -cospi8], [cospi8, sinpi8]]))

rep = representation.SageMatrixRepresentation(relations=["adCbADcB"],
                                        base_ring=QQbar)

rep["a"] = g1
rep["b"] = g2
rep["c"] = g3
rep["d"] = g4

rep.elements(rep.relations)

[
[1.000000000000?         0.?e-12]
[        0.?e-12 1.000000000000?]
]

In [3]:
rep.cocycle_matrix()

[ 3.41421356237310? -10.1333432997419?   -7.165355763339?   -8.579569325712?  12.3307115266775?  13.5475568621150?  -1.5537739740301?  -4.9679875364032?]
[-0.47648905024951?   3.4142135623731?    1.077284923781?    0.336928638593?  -2.9377245121236?  -2.6738572771852?   1.8604395883431?   1.5537739740301?]

In [4]:
words.formal_inverse("abAAB")

'baaBA'

In [5]:
rep.cocycle_matrix() * rep.coboundary_matrix()

[0.?e-12 0.?e-12]
[0.?e-11 0.?e-12]

In [6]:
adj = rep.sln_adjoint()

In [7]:
adj.elements(adj.relations)[0] == utils.identity(3, like=adj)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
ir3 = rep.compose(lie.hom.sl2_irrep(4))

ir3.elements(ir3.relations)

[
[1 0 0 0]
[0 1 0 0]
[0 0 1 0]
[0 0 0 1]
]

In [9]:
num_rep = representation.Representation(
    rep.change_dtype('float64')
)

num_rep.elements(num_rep.relations)

array([[[ 1.00000000e+00,  4.74876365e-14],
        [-2.92352062e-15,  1.00000000e+00]]])

In [10]:
numadj = num_rep.sln_adjoint()
numadj.elements(num_rep.relations)

array([[[ 1.00000000e+00, -4.34704133e-14,  3.19488395e-13],
        [ 4.22481424e-12,  1.00000000e+00,  1.04343496e-11],
        [-1.24859226e-13,  1.80892652e-14,  1.00000000e+00]]])

In [11]:
num_ir5 = num_rep.compose(lie.hom.sl2_irrep(5))

#pretty intense round-off error, we're only correct to 6 decimals places...
np.abs(num_ir5.elements(num_rep.relations) - utils.identity(5)) < 1e-6

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])